phrase = input("Veuillez saisir une phrase : ")
phrase_maj = phrase.upper()
print("En majuscules : ", phrase_maj)
phrase_min = phrase.lower()
print("En minuscules : ", phrase_min)
nombre_mots = len(phrase)
print("Nombre de mots : ", nombre_mots)